FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata \
    && apt install -y --no-install-recommends apt-utils python3-venv python3-pip  \
    && apt install -y git default-jre && apt clean

# Activate virtualenv (https://pythonspeed.com/articles/activate-virtualenv-dockerfile/)
ENV VIRTUAL_ENV=/root/python-environments/fastapi-env
RUN mkdir /root/python-environments && python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV PYTHONPATH=/root/statsapi
