version: "3.8"
services:
  statsapi:
    image: javierjsa/stats-api:latest    
    ports:
      - 80:8000
    env_file:
      - .env
    volumes:
      - ./statsapi:/root/statsapi/statsapi
    depends_on:
      - minio
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data
    env_file:
      - .env
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c " sleep 10;
      /usr/bin/mc alias set minio-local http://minio:9000 minio minio123;
      /usr/bin/mc admin user add minio-local  apiuser  'serv-account-apiuser';
      /usr/bin/mc admin user svcacct add --access-key 'serv-account-apiuser' --secret-key 'secret-key-apiuser' minio-local apiuser;
      /usr/bin/mc admin policy attach minio-local readwrite --user apiuser;
      /usr/bin/mc mb --ignore-existing minio-local/databucket;
      exit 0;
      "
volumes:
  datastore:
    name: datastore
