name: Build and push stats-api image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build latest the Docker image
      run: docker build  --file Dockerfile --tag javierjsa/stats-api:latest .
    - name: Tag image with commit hash
      run: docker tag javierjsa/stats-api:latest javierjsa/stats-api:$(git rev-parse --short "$GITHUB_SHA")
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Push latest tag to dockerhub
      run: docker push javierjsa/stats-api:latest
    - name: Push commit tag to dockerhub
      run: docker push javierjsa/stats-api:$(git rev-parse --short "$GITHUB_SHA")

